### ISSUE TITLE
ConexionDB.jaba

### ISSUE THREAD

**Issue by RMestas** [DiscoDurodeRoer/Gestor-de-clases#1]
/**
     * Cuenta el numero de registros
     * @param tabla Nombre de la tabla de la base de datos
     * @param condicion Condicion (sin where) 
     * @return Número de registros de la consulta
     */
    public int cuentaRegistrosConsulta(String tabla, String condicion){
        
        String consulta;
        
        if (condicion.equals("")){
            consulta="select count(*) from "+tabla;
        }else{
            consulta="select count(*) from "+tabla+" where "+condicion;
        }
        
        try (Statement sentenciaAux = conexion.createStatement();
                ResultSet aux = sentenciaAux.executeQuery(consulta);) {
            
            
            return aux.getInt(0);  
            
        } catch (SQLException ex) {
            Logger.getLogger(ConexionDB.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
               
    }
   
Este método siempre me devuelve -1. Creo que lo estoy usando correctamente. Me puedes confirmar que funciona bien??

Gracias!!!!.
Edito:  
return aux.getInt(0);  ----> return aux.getInt(1);
entonces funciona!!!

**Comment by DiscoDurodeRoer** [comment]
Solucionado. 
https://github.com/DiscoDurodeRoer/Biblioteca-DDR-Java/commit/9722cfed714a8b50f4c231ac1aee0d2913cbcc15

Todas las dudas relacionadas con la base de datos Conexion, realizarlas en la biblioteca de DDR
https://github.com/DiscoDurodeRoer/Biblioteca-DDR-Java/issues
